In [ ]:
!pip install tensorflow==2.19.1

In [ ]:
import tensorflow as tf
print(tf.__version__)
print(tf.test.is_gpu_available())

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


2.19.1
False


# Tensorflow Operations

## Arithmetic Operation

In TensorFlow, a constant is a tensor whose value cannot change once it is created. Think of it like a fixed number or array stored in memory that TensorFlow will always treat as the same.

Difference between constant and variable in TensorFlow

| Feature    | tf.constant                 | tf.Variable                     |
| ---------- | --------------------------- | ------------------------------- |
| Mutability | Cannot change               | Can change (trainable)          |
| Use case   | Fixed values in computation | Model parameters (weights/bias) |
| Example    | `tf.constant([1,2,3])`      | `tf.Variable([1,2,3])`          |


In [ ]:
import tensorflow as tf

# Create tensors
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

# Addition
print(tf.add(a, b))

# Subtraction
print(tf.subtract(a, b))

# Multiplication
print(tf.multiply(a, b))

# Division
print(tf.divide(a, b))

# Power
print(tf.pow(a, 2))

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)
tf.Tensor([1 4 9], shape=(3,), dtype=int32)


## Reduction Operations

In [ ]:
x = tf.constant([1, 2, 3, 4])

print("Sum:", tf.reduce_sum(x))
print("Mean:", tf.reduce_mean(x))
print("Max:", tf.reduce_max(x))
print("Min:", tf.reduce_min(x))

Sum: tf.Tensor(10, shape=(), dtype=int32)
Mean: tf.Tensor(2, shape=(), dtype=int32)
Max: tf.Tensor(4, shape=(), dtype=int32)
Min: tf.Tensor(1, shape=(), dtype=int32)


## Trigonometric Operations

In [ ]:
angle = tf.constant([0.0, 3.14159/2, 3.14159])  # in radians

print("Sine:", tf.sin(angle))
print("Cosine:", tf.cos(angle))
print("Tangent:", tf.tan(angle))

Sine: tf.Tensor([0.0000000e+00 1.0000000e+00 2.5351817e-06], shape=(3,), dtype=float32)
Cosine: tf.Tensor([ 1.0000000e+00  1.2675908e-06 -1.0000000e+00], shape=(3,), dtype=float32)
Tangent: tf.Tensor([ 0.0000000e+00  7.8889806e+05 -2.5351817e-06], shape=(3,), dtype=float32)


## Linear Algebra Operations

In [ ]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

print("Matrix Multiply:\n", tf.matmul(a, b))
print("Transpose:\n", tf.transpose(a))

Matrix Multiply:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
Transpose:
 tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


## Comparison Operations

In [ ]:
x = tf.constant([1, 2, 3])
y = tf.constant([3, 2, 1])

print(tf.equal(x, y))
print(tf.greater(x, y))
print(tf.less_equal(x, y))

tf.Tensor([False  True False], shape=(3,), dtype=bool)
tf.Tensor([False False  True], shape=(3,), dtype=bool)
tf.Tensor([ True  True False], shape=(3,), dtype=bool)


## Slicing

In [ ]:
# 1D tensor
a = tf.constant([10, 20, 30, 40, 50])

# Slice from index 1 to 3 (3 not included)
print(a[1:4])

# Slice from start to index 2
print(a[:3])

# Slice from index 2 to end
print(a[2:])

# Slice with step
print(a[::2])

tf.Tensor([20 30 40], shape=(3,), dtype=int32)
tf.Tensor([10 20 30], shape=(3,), dtype=int32)
tf.Tensor([30 40 50], shape=(3,), dtype=int32)
tf.Tensor([10 30 50], shape=(3,), dtype=int32)


In [ ]:
# 2D tensor
b = tf.constant([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Slice first two rows, all columns
print(b[:2, :])

# Slice all rows, first two columns
print(b[:, :2])

# Slice a submatrix (rows 1-2, columns 1-2)
print(b[1:, 1:3])

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[5 6]
 [8 9]], shape=(2, 2), dtype=int32)


In [ ]:
# tf.slice(input, begin, size)
# begin: starting index
# size: number of elements to take

c = tf.constant([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

# Take 2 rows, 2 columns starting from (0,1)
sliced = tf.slice(c, [0, 1], [2, 2])
print(sliced)
# [[20 30]
#  [50 60]]

tf.Tensor(
[[20 30]
 [50 60]], shape=(2, 2), dtype=int32)


## Broadcasting

In [ ]:
a = tf.constant(5)  # scalar
b = tf.broadcast_to(a, [3])
print(b)

tf.Tensor([5 5 5], shape=(3,), dtype=int32)


# Placeholder

A placeholder is a tensor that we declare, but we don’t give it a value yet.

You can feed it data later during computation.

Placeholders were mainly used in TensorFlow 1.x to build computational graphs before running them.

In TensorFlow 2.x (eager execution), placeholders are no longer needed, because you can directly pass data to tensors or functions.

In [ ]:
tf.disable_v2_behavior()  # Disable TF2 behavior

# Create a placeholder for a float32 tensor
x = tf.placeholder(tf.float32, shape=(None, 2))  # None means any number of rows
y = tf.placeholder(tf.float32, shape=(None, 2))

# Define an operation
z = x + y

with tf.Session() as sess:
    # Feed values to placeholders
    result = sess.run(z, feed_dict={x: [[1,2],[3,4]], y: [[5,6],[7,8]]})
    print(result)

[[ 6.  8.]
 [10. 12.]]


# Computational Graph

A computational graph is a network of nodes and edges that represents mathematical computations.

- Nodes: represent operations (like addition, multiplication, or functions) or variables/constants.
- Edges: represent tensors (data) flowing between operations.

- It allows TensorFlow to optimize and run computations efficiently.

Think of it like a flowchart of math operations, where data flows through a network of operations to produce the result.

### Why Computational Graphs?

- Lazy execution (in TF1.x): You can define all operations first, then execute them later with specific inputs.

- Optimizations: TensorFlow can parallelize operations and run efficiently on CPU, GPU, or TPU.

- Automatic differentiation: TensorFlow can compute gradients for training neural networks automatically.

In [ ]:
tf.disable_v2_behavior()  # Disable eager execution

# Define placeholders (inputs)
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

# Define operations (nodes in the graph)
z = x * y + 2

# Create a session to execute the graph
with tf.Session() as sess:
    result = sess.run(z, feed_dict={x: 3, y: 4})
    print(result)  # 14

14.0


# Session

A session is a runtime environment in TensorFlow 1.x where computational graphs are executed.

In TensorFlow 1.x, you define the graph first (placeholders, operations, constants)

Then, you run the graph inside a session using sess.run().

Think of a session as the engine that actually computes the results.

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()  # Disable TF2 eager execution

# Define a computational graph
a = tf.constant(5)
b = tf.constant(3)
c = a + b  # Operation node

# Create a session
with tf.Session() as sess:
    result = sess.run(c)  # Execute the graph
    print(result)

8
